CREATE SCHEMA IF NOT EXISTS activity_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA activity_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA activity_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;

